import { Bot } from 'lucide-react';

export default function AiDisclosure() {
  return (
    <div className="bg-blue-50 border border-blue-200 rounded-lg px-4 py-3 flex items-start gap-3">
      <Bot className="h-5 w-5 text-blue-600 shrink-0 mt-0.5" />
      <div className="text-xs text-blue-700">
        <p className="font-medium mb-1">AI-Assisted Classification</p>
        <p>
          This classification was generated by an AI model. A human reviewer must
          verify all fields before approving. The AI's confidence score and
          reasoning are provided to assist — not replace — your professional
          judgment.
        </p>
      </div>
    </div>
  );
}
